#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd ./client/src/test 

CHECK_LOCATION='<project_root>/client/src/test'
if git diff --name-only | grep -q $CHECK_LOCATION; then
  # next line is a placeholder
  echo 'found match'  
  npm test
  exit 0
else
  echo 'no match'
  exit 0
fi